sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "iojs-2"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g npm@3.x
before_script:
  - npm prune
after_script:
  - npm run coverage
  - npm run coveralls