language: node_js
node_js:
  - "iojs-2"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run coverage
  - npm run build
before_install:
  - npm install -g npm@3.x
after_success: coveralls